<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mailjet.Api" Version="4.0.1" />
    <PackageReference Include="Stripe.net" Version="52.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BulkyBook.DataAccess\BulkyBook.DataAccess.csproj" />
    <ProjectReference Include="..\BulkyBook.Models\BulkyBook.Models.csproj" />
    <ProjectReference Include="..\BulkyBook.Utiltiy\BulkyBook.Utiltiy.csproj" />
  </ItemGroup>

</Project>
